export const EPOXY_REVIEWS = [
  { quote: "They transformed my stained garage floor into a gorgeous, clean space. The flake finish looks amazing and cleans up so easily!", author: "Steven M.", location: "Tampa, FL" },
  { quote: "Fast, professional, and very neat. They completed our commercial warehouse floor over the weekend so we had zero downtime.", author: "Amanda K.", location: "St. Petersburg, FL" },
  { quote: "Excellent work. The pricing was fair, and the team was extremely detailed with the concrete prep. Highly recommend!", author: "Jason D.", location: "Brandon, FL" },
  { quote: "I am thrilled with my new metallic epoxy floor. It looks like liquid marble. Truly a work of art!", author: "Sarah P.", location: "Clearwater, FL" },
  { quote: "Reliable company. They arrived on time, completed the work as promised, and left the workspace spotless.", author: "Robert L.", location: "Lutz, FL" },
  { quote: "Our garage floor had several deep cracks and oil stains. After diamond grinding and patching, the new epoxy looks flawless.", author: "David T.", location: "Riverview, FL" },
  { quote: "The polyaspartic topcoat makes a huge difference. Highly scratch resistant and completely slip-resistant even when wet.", author: "Linda W.", location: "Wesley Chapel, FL" },
  { quote: "Great customer service from start to finish. They explained the steps clearly and helped us choose the perfect flake color.", author: "Michael B.", location: "Valrico, FL" },
  { quote: "Installed a solid gray epoxy in our dog grooming salon. It stands up to water, mud, and claws perfectly. So easy to clean!", author: "Karen S.", location: "Carrollwood, FL" },
  { quote: "Highly professional crew. They used advanced dust collection during the grinding phase, so there was almost zero dust in the house.", author: "James H.", location: "Temple Terrace, FL" },
  { quote: "Very impressed with the efficiency. Done in just two days. Our garage looks like a high-end showroom now.", author: "Patricia G.", location: "Dunedin, FL" },
  { quote: "We had our commercial kitchen floor coated with commercial slip-resistant epoxy. It has improved safety and looks fantastic.", author: "Charles F.", location: "Safety Harbor, FL" },
  { quote: "Superb communication. The quote was transparent, no hidden fees, and the installers were polite and hard-working.", author: "John R.", location: "Pinellas Park, FL" },
  { quote: "The metallic ocean blue epoxy floor in my home office is stunning. Everyone who visits asks about it immediately.", author: "Barbara M.", location: "Largo, FL" },
  { quote: "They did an outstanding job coating our outdoor patio floor. It holds up perfectly to Florida rain and intense sun.", author: "Joseph Y.", location: "Seminole, FL" },
  { quote: "We went with the 'Tuxedo' flake pattern. The color distribution is uniform and the topcoat feels thick and premium.", author: "Susan B.", location: "Tarpon Springs, FL" },
  { quote: "Fast turnaround and high quality. They did our retail storefront overnight. Extremely pleased with the results.", author: "Thomas N.", location: "Tampa, FL" },
  { quote: "Perfect application. They paid extra attention to the stem walls, coating them to match the floor. Excellent detail.", author: "Jessica R.", location: "Brandon, FL" },
  { quote: "Our basement was damp and ugly. They sealed the concrete and put down a beautiful flake epoxy. Now it's a usable room!", author: "Richard P.", location: "St. Petersburg, FL" },
  { quote: "Very professional team. They helped move our heavy appliances out before starting and put them back carefully. Great service.", author: "Lisa A.", location: "Clearwater, FL" },
  { quote: "The metallic copper color we chose has a 3D effect that looks incredible under garage lighting. Worth every penny.", author: "Christopher E.", location: "Riverview, FL" },
  { quote: "No more hot tire pickup! Our old DIY floor peeled within a year, but this professional coating is solid as a rock.", author: "Nancy K.", location: "Lutz, FL" },
  { quote: "Outstanding commercial work. They coated 5,000 sq ft for us in St. Pete. Fast, clean, and highly durable.", author: "Daniel O.", location: "St. Petersburg, FL" },
  { quote: "My garage is finally organized and clean, all starting with this amazing new floor. Excellent workmanship.", author: "Betty J.", location: "Valrico, FL" },
  { quote: "Highly recommend this company. Their warranty is outstanding and the floor looks even better than we hoped.", author: "Matthew S.", location: "Carrollwood, FL" },
  { quote: "The texture they added ensures it's not slippery, which was my wife's main concern. Perfect balance of looks and safety.", author: "Sandra L.", location: "Wesley Chapel, FL" },
  { quote: "Excellent job on our showroom floor. The reflection makes the entire room brighter and more professional.", author: "Donald C.", location: "Tampa, FL" },
  { quote: "Great team. Courteous, prompt, and very focused on quality control. They prepped the concrete perfectly.", author: "Ashley M.", location: "Dunedin, FL" },
  { quote: "I love our new metallic silver laundry room floor. It's clean, bright, and completely waterproof.", author: "Kimberly W.", location: "Pinellas Park, FL" },
  { quote: "Professional grade equipment and materials. They diamond ground the slab to perfection before applying the epoxy.", author: "Paul R.", location: "Largo, FL" },
  { quote: "Our auto shop floor has taken a beating from dropped tools and jack stands, and the coating still looks new.", author: "George H.", location: "Tampa, FL" },
  { quote: "Very pleased with the flake option we chose. It hides dust and debris perfectly, making the garage look clean always.", author: "Kenneth D.", location: "Brandon, FL" },
  { quote: "Awesome experience. From estimation to completion, the entire process was seamless and professional.", author: "Donna F.", location: "Clearwater, FL" },
  { quote: "They fixed the pooling water issue on our garage floor and coated it beautifully. High-quality work.", author: "Steven V.", location: "Riverview, FL" },
  { quote: "Very competitive pricing for the level of industrial prep and polyaspartic coatings they use. Highly recommend.", author: "Edward K.", location: "Lutz, FL" },
  { quote: "The crew worked hard and finished our large garage in under 24 hours. The flake finish looks spectacular.", author: "Carol Z.", location: "Wesley Chapel, FL" },
  { quote: "Professional, reliable, and detailed. The border cuts are extremely sharp and clean. Fantastic job.", author: "Ronald B.", location: "Valrico, FL" },
  { quote: "We coated our patio floor with a custom tan flake mix. It blends beautifully with our pool deck.", author: "Michelle P.", location: "Seminole, FL" },
  { quote: "Outstanding results. The gloss level is perfect, and it is incredibly easy to sweep and mop.", author: "Gary S.", location: "Tampa, FL" },
  { quote: "A first-class experience. The crew was respectful of our property and kept us updated on each phase.", author: "Melissa A.", location: "St. Petersburg, FL" },
  { quote: "Our commercial restroom floor is now seamless, clean, and complies with all health department codes. Great work.", author: "Brian K.", location: "Brandon, FL" },
  { quote: "The metallic charcoal epoxy looks high-end and luxurious. It completely transformed our studio space.", author: "Amy L.", location: "Tarpon Springs, FL" },
  { quote: "They repaired extensive spalling and pitting on our old slab before coating. You would never know there was damage.", author: "Kevin T.", location: "Carrollwood, FL" },
  { quote: "They showed up exactly when they said they would and completed the garage floor without any issues. Excellent team.", author: "Helen J.", location: "Lutz, FL" },
  { quote: "We chose the full-broadcast flake system. The floor is dense, textured, and feels incredibly solid underfoot.", author: "Jerry W.", location: "Clearwater, FL" },
  { quote: "Absolutely love the garage floor. No more dusty concrete tracking into the house. It's a game-changer.", author: "Amanda E.", location: "Dunedin, FL" },
  { quote: "Their floor prep is what sets them apart. They spent hours grinding and patching before any epoxy went down.", author: "Jason C.", location: "Riverview, FL" },
  { quote: "Very professional estimation process with samples. The final installation matched the sample board perfectly.", author: "Sarah B.", location: "Valrico, FL" },
  { quote: "Highly durable product. Spilled oil and brake fluid wiped right off without leaving any stain or trace.", author: "Robert G.", location: "Tampa, FL" },
  { quote: "Best home improvement decision we've made. The garage feels like an extension of our living space now.", author: "Jeffrey H.", location: "Wesley Chapel, FL" }
];

export const TREE_REVIEWS = [
  { quote: "They removed a massive oak tree close to my house. The team was incredibly precise, fast, and cleaned up every single leaf!", author: "Thomas B.", location: "Tampa, FL" },
  { quote: "Excellent tree pruning service. Our palms look healthy and beautiful now. Very reasonable price.", author: "Linda G.", location: "Clearwater, FL" },
  { quote: "Quick response for emergency tree limb removal after a storm. They saved our roof from serious damage!", author: "David R.", location: "St. Petersburg, FL" },
  { quote: "Professional crew, great communication, and competitive pricing. I'll definitely use them again.", author: "Karen M.", location: "Brandon, FL" },
  { quote: "Highly recommend. They are knowledgeable about tree health and gave great advice on preserving our oaks.", author: "James H.", location: "Riverview, FL" },
  { quote: "The best tree removal crew in Tampa. They worked safely, used advanced rigging, and left my property spotless.", author: "Michael D.", location: "Lutz, FL" },
  { quote: "They did an amazing job trimming back several large branches hanging over my screen enclosure. No damage at all.", author: "Sarah F.", location: "Wesley Chapel, FL" },
  { quote: "Excellent stump grinding service. They ground it down deep and cleaned up all the wood chips. Highly recommend.", author: "John S.", location: "Valrico, FL" },
  { quote: "Very professional and certified arborists. They diagnosed a disease in our pine trees and helped save them.", author: "Robert P.", location: "Carrollwood, FL" },
  { quote: "Prompt emergency response. A massive branch fell across our driveway, and they cleared it within two hours of calling.", author: "Patricia W.", location: "Temple Terrace, FL" },
  { quote: "Highly skilled crew. Watching them take down a huge dead tree in a tight space between houses was impressive.", author: "James M.", location: "Dunedin, FL" },
  { quote: "Fair pricing, quick scheduling, and professional execution. They hauled away all wood and debris as promised.", author: "Elizabeth H.", location: "Safety Harbor, FL" },
  { quote: "Our oak trees look healthy and beautifully shaped now. They really understand proper arboriculture.", author: "William J.", location: "Pinellas Park, FL" },
  { quote: "Great customer service. They took the time to answer all my questions and gave a very detailed, written quote.", author: "Jennifer C.", location: "Largo, FL" },
  { quote: "Professional tree care at its best. Safe, efficient, and very respectful of our landscaping. Five stars.", author: "David B.", location: "Seminole, FL" },
  { quote: "They cleaned up my overgrown backyard, removing dead trees and vines. It looks twice as big now!", author: "Mary L.", location: "Tarpon Springs, FL" },
  { quote: "Certified arborist on site was a huge plus. They helped guide us on what needed trimming for local permit codes.", author: "Richard S.", location: "Tampa, FL" },
  { quote: "They ground down five large oak stumps in our backyard. Fast, clean, and very reasonable pricing.", author: "Joseph A.", location: "Brandon, FL" },
  { quote: "The crew was polite, hard-working, and went above and beyond to clean up the yard. Outstanding company.", author: "Susan O.", location: "St. Petersburg, FL" },
  { quote: "They handled a complex crane-assisted tree removal near power lines flawlessly. Absolute pros.", author: "Charles T.", location: "Clearwater, FL" },
  { quote: "Our palms look spectacular after their trimming service. They removed all the seed pods and dead fronds.", author: "Barbara N.", location: "Riverview, FL" },
  { quote: "Very reasonable quote compared to others in the area, and the quality of work was exceptional.", author: "Matthew K.", location: "Lutz, FL" },
  { quote: "They pruned several grand oaks on our property, respecting the city guidelines. Professional and knowledgeable.", author: "Jessica H.", location: "Tampa, FL" },
  { quote: "Fast service, professional team, and top-tier equipment. They completed a large clearing project in one day.", author: "Christopher G.", location: "Wesley Chapel, FL" },
  { quote: "Highly recommend their emergency tree removal. They cleared a fallen tree off my fence quickly and safely.", author: "Nancy E.", location: "Valrico, FL" },
  { quote: "They trimmed our pine trees to prepare for hurricane season. Great peace of mind knowing the canopy is thinned.", author: "Daniel V.", location: "Carrollwood, FL" },
  { quote: "The crew did an outstanding job removing a large dead palm and grinding the stump. Very neat work.", author: "Sandra R.", location: "Dunedin, FL" },
  { quote: "Professional, friendly, and efficient. They left our front yard cleaner than it was before they started.", author: "Thomas W.", location: "Pinellas Park, FL" },
  { quote: "Excellent communication throughout the process. They kept us updated on their arrival time and progress.", author: "Donna J.", location: "Largo, FL" },
  { quote: "We have used them twice for tree trimming, and they have been prompt and professional both times.", author: "Paul F.", location: "Seminole, FL" },
  { quote: "They took down a diseased maple tree safely. Very detailed cleanup, including raking all small twigs.", author: "George D.", location: "Tampa, FL" },
  { quote: "Knowledgeable, professional, and well-equipped. They made a difficult tree removal look easy.", author: "Lisa M.", location: "Brandon, FL" },
  { quote: "Great experience. The team was highly coordinated, worked safely, and finished the job ahead of schedule.", author: "Kevin B.", location: "Clearwater, FL" },
  { quote: "They did a great job pruning our fruit trees. Looking forward to a healthy harvest next season.", author: "Betty T.", location: "Riverview, FL" },
  { quote: "Courteous crew and excellent management. They made sure our gates were closed to keep our pets safe.", author: "Ronald C.", location: "Lutz, FL" },
  { quote: "Prompt estimate, fair price, and excellent tree pruning. Will definitely use them for all our tree care.", author: "Sandra S.", location: "Wesley Chapel, FL" },
  { quote: "They removed a large pine tree that was leaning towards our house. Very precise rigging and safe removal.", author: "Donald M.", location: "Valrico, FL" },
  { quote: "Cleaned up all our palms and trimmed back the oak trees. Very thorough work and polite crew.", author: "Helen R.", location: "Carrollwood, FL" },
  { quote: "The stump grinding was quick, and they even spread the mulch in my garden beds as requested. Excellent service.", author: "Jerry P.", location: "Tampa, FL" },
  { quote: "Reliable and professional. They showed up on time, worked hard, and charged exactly what was quoted.", author: "Jason Z.", location: "St. Petersburg, FL" },
  { quote: "Excellent canopy lifting on our old oaks. It lets so much more light into our yard now. Beautiful job.", author: "Amanda G.", location: "Brandon, FL" },
  { quote: "Prompt response to my request for a quote, and they were out the next week to do the trimming. Very efficient.", author: "Jeffrey O.", location: "Dunedin, FL" },
  { quote: "They did an incredible job clearing out large limbs that were scraping against our gutters. Safe and fast.", author: "Gary D.", location: "Largo, FL" },
  { quote: "Highly recommend for grand oak pruning. They are certified arborists who know how to protect the tree.", author: "Melissa L.", location: "Seminole, FL" },
  { quote: "Professional crew with safety gear. They worked quickly to remove a storm-damaged tree from our backyard.", author: "Brian F.", location: "Tampa, FL" },
  { quote: "Great price for stump removal and tree pruning. They left the yard clean and tidy. Will hire again.", author: "Amy Y.", location: "Riverview, FL" },
  { quote: "They did a flawless job cutting down a dead palm tree near our pool cage. Extremely precise work.", author: "Kevin V.", location: "Lutz, FL" },
  { quote: "Very professional arborist consulting. They helped us understand which trees were protected and which could be removed.", author: "Sarah W.", location: "Wesley Chapel, FL" },
  { quote: "They removed several trees along our property line. Very neat work, didn't disturb the neighboring yard.", author: "Robert N.", location: "Valrico, FL" },
  { quote: "The tree crew was highly professional and polite. They cleaned up every branch and blew off the driveway. Fantastic service.", author: "Thomas K.", location: "Tampa, FL" }
];

export const PAVING_REVIEWS = [
  { quote: "The new paver patio and driveway look stunning! It has completely changed the curb appeal of our home.", author: "Mark S.", location: "Tampa, FL" },
  { quote: "Excellent concrete driveway installation. They reinforced it properly and finished it perfectly. Solid work.", author: "Jeffrey W.", location: "Brandon, FL" },
  { quote: "Great crew. They worked fast, poured a beautiful new slab for our workshop, and left the yard clean.", author: "Brian O.", location: "Lutz, FL" },
  { quote: "Our pool deck was cracked and ugly. They repaved it with gorgeous pavers. Outstanding transformation!", author: "Melissa T.", location: "Clearwater, FL" },
  { quote: "Very pleased with the custom walkway. Professional communication and high-quality craftsmanship.", author: "Sandra L.", location: "St. Petersburg, FL" },
  { quote: "We had our old asphalt driveway replaced with concrete. The team did a flawless job grading and pouring. Excellent result.", author: "David M.", location: "Riverview, FL" },
  { quote: "They installed a beautiful paver patio in our backyard complete with a fire pit area. It is our new favorite spot.", author: "Sarah H.", location: "Wesley Chapel, FL" },
  { quote: "Highly professional contractors. They explained the drainage layout and made sure the slope was perfect before paving.", author: "Michael P.", location: "Valrico, FL" },
  { quote: "Great job extending our driveway slab. The seam is smooth and the color match is spot on. Very happy.", author: "John G.", location: "Carrollwood, FL" },
  { quote: "Excellent work on our commercial concrete sidewalk. They finished on time and handled all city code inspections.", author: "Robert T.", location: "Temple Terrace, FL" },
  { quote: "Our paver driveway was sinking in areas. They lifted the old pavers, compacted the base, and re-laid them perfectly.", author: "Patricia B.", location: "Dunedin, FL" },
  { quote: "Prompt, professional, and detailed. The stamped concrete walkway looks exactly like natural flagstone.", author: "James F.", location: "Safety Harbor, FL" },
  { quote: "Excellent paver sealing service. It brought back the vibrant color and protects against weeds and stains.", author: "Elizabeth R.", location: "Pinellas Park, FL" },
  { quote: "The team did a fantastic job pouring our new backyard patio. Safe, clean, and highly skilled crew.", author: "William K.", location: "Largo, FL" },
  { quote: "Very competitive pricing for the high quality of pavers and base preparation they use. Highly recommend.", author: "Jennifer S.", location: "Seminole, FL" },
  { quote: "They replaced our cracked pool deck concrete with modern shell pavers. It stays cool underfoot and looks beautiful.", author: "David A.", location: "Tarpon Springs, FL" },
  { quote: "Highly professional crew. They grade the yard perfectly to ensure rainwater flows away from the house structure.", author: "Mary W.", location: "Tampa, FL" },
  { quote: "They installed a retaining wall and paver path in our front yard. The craftsmanship is absolutely outstanding.", author: "Richard L.", location: "Brandon, FL" },
  { quote: "Great communication from the project manager. They kept us updated on delivery dates and weather delays.", author: "Joseph C.", location: "St. Petersburg, FL" },
  { quote: "They poured a 20x30 concrete pad for our new garage. The finish is smooth and level. Excellent construction.", author: "Susan D.", location: "Clearwater, FL" },
  { quote: "The herringbone paver pattern they did on our driveway is a work of art. Our neighbors have all complimented it.", author: "Charles E.", location: "Riverview, FL" },
  { quote: "Very professional excavation and prep work. They spent a full day compacting the sub-base, which is key for longevity.", author: "Barbara M.", location: "Lutz, FL" },
  { quote: "They replaced our old cracked walkway with beautiful gray pavers. It makes the house entry look so welcoming.", author: "Matthew N.", location: "Tampa, FL" },
  { quote: "Excellent repair job. They cut out and replaced a section of concrete that was lifted by tree roots. Smooth finish.", author: "Jessica P.", location: "Wesley Chapel, FL" },
  { quote: "We hired them for a custom brick paver pool surround. The cuts around the curved edge are incredibly neat.", author: "Nancy G.", location: "Valrico, FL" },
  { quote: "Professional, clean, and fast. They completed our new paver driveway in just three days from start to finish.", author: "Daniel B.", location: "Carrollwood, FL" },
  { quote: "They did a great job on our concrete driveway slab. Reinforced with rebar, cut joints perfectly, and broom finished.", author: "Sandra K.", location: "Dunedin, FL" },
  { quote: "Fantastic service. They cleared our old patio, leveled the ground, and laid a perfect paver layout. Highly recommend.", author: "Thomas O.", location: "Pinellas Park, FL" },
  { quote: "Excellent project management. They handled the HOA design approval and city permits for us. Very stress-free.", author: "Donna H.", location: "Largo, FL" },
  { quote: "Our stamped concrete patio looks amazing. They applied a beautiful charcoal border that contrasts nicely.", author: "Paul Y.", location: "Seminole, FL" },
  { quote: "They replaced our broken concrete driveway with high-quality brick pavers. It has boosted our home value.", author: "George S.", location: "Tampa, FL" },
  { quote: "The concrete crew was highly skilled. Poured a perfectly flat garage slab and finished it smoothly.", author: "Lisa V.", location: "Brandon, FL" },
  { quote: "Great customer service. The design consultation helped us choose the right paver style and border color.", author: "Kevin C.", location: "Clearwater, FL" },
  { quote: "They did a beautiful job paving our backyard patio. The crew worked hard and cleaned up completely.", author: "Betty M.", location: "Riverview, FL" },
  { quote: "Prompt estimate, fair price, and excellent paver installation. Will use them again for our next project.", author: "Ronald L.", location: "Lutz, FL" },
  { quote: "Highly professional stamped concrete installation. The texture and release colors look extremely natural.", author: "Sandra T.", location: "Wesley Chapel, FL" },
  { quote: "They removed our old wood deck and replaced it with a durable concrete paver patio. Much lower maintenance!", author: "Donald P.", location: "Valrico, FL" },
  { quote: "The crew did an excellent job grading the backyard before paving. The slope is correct and drains perfectly.", author: "Helen A.", location: "Carrollwood, FL" },
  { quote: "They installed a custom driveway apron using cobblestone pavers. It looks very elegant and handles loads well.", author: "Jerry J.", location: "Tampa, FL" },
  { quote: "Outstanding results. The paver driveway holds up perfectly to our heavy SUV and trailer. High-quality work.", author: "Jason R.", location: "St. Petersburg, FL" },
  { quote: "They installed an elegant paver walkway around the side of our house. Very clean borders and leveling.", author: "Amanda D.", location: "Brandon, FL" },
  { quote: "Professional concrete contractors. They arrived on time, completed the pour efficiently, and kept the site safe.", author: "Jeffrey S.", location: "Dunedin, FL" },
  { quote: "Our driveway looks brand new. The concrete wash and paver installation were both handled professionally.", author: "Gary B.", location: "Largo, FL" },
  { quote: "Outstanding craftsmanship on our brick paver patio. They built a custom step down that looks beautiful.", author: "Melissa W.", location: "Seminole, FL" },
  { quote: "Prompt and professional driveway extension. The concrete matches the existing slab texture perfectly.", author: "Brian E.", location: "Tampa, FL" },
  { quote: "They did a great job paving our commercial store entrance. Safe walkway and met all ADA slope codes.", author: "Amy C.", location: "Riverview, FL" },
  { quote: "They took down our old retaining wall and rebuilt a beautiful block wall with a paver landing. Stellar job.", author: "Kevin K.", location: "Lutz, FL" },
  { quote: "Very professional design consultation. They brought layout diagrams and paver samples to our house.", author: "Sarah T.", location: "Wesley Chapel, FL" },
  { quote: "They did an incredible job laying brick pavers on our old concrete patio. Completely refreshed the space.", author: "Robert O.", location: "Valrico, FL" },
  { quote: "Highly coordinate masonry crew. Laid thousands of pavers with perfect alignment, clean cuts, and compacted joints.", author: "Thomas F.", location: "Tampa, FL" }
];
